title: Create a college notebook
tagline: A brand new course on Learning Lab
description: Let's create a college notebook
template:
  repo: create-a-college-notebook-template
  name: college-notebook
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Configuring your workflow
    description: Preparing your repository for GitHub Actions
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: createPullRequest
        title: Your workflow
        head: add-workflow
        base: master
      - type: respond
        with: REPLACE-WITH-RESPONSE
  - title: Move the workflow file
    actions:
      - type: getTree
        action_id: tree
        recursive: true
        sha: '%payload.pull_request.head.sha%'
      - type: gate
        left: '%actions.tree.data.tree%'
        operator: includes
        right: 'path:.github/workflows/workflow.yml'
        else:
          - type: respond
            with: fail.md
      - type: mergePullRequest
      - type: createPullRequest
        title: First action to start notebook
        body: response-file.md
        head: add-issue-action
        base: master
        action_id: new_pr
      - type: respond
        with: response.md
    description: Move your wokflow file
    link: '{{ repoUrl }}/pulls/2'
    event: pull_request.synchronize
  - title: First Action
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: createPullRequest
        title: Saving our notes
        body: response-file.md
        head: add-save-action
        base: master
        action_id: save_issue_body
      - type: respond
        with: response.md
    description: Your first action
    link: '{{ repoUrl }}/pulls/3'
    event: pull_request.closed
  - title: Add IOS notification
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: createIssue
        title: How to set up push notifications
        body: response-file.md
      - type: respond
        with: other-ideas.md
    description: Adding our IOS notfication
    link: '{{ repoUrl }}/issues/4'
    event: pull_request.closed
